
spring:
  profiles:
    include:
#      - h2
      - mysql
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: pers.clare.core.data.MyPhysicalNamingStrategy
    database: mysql

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
    mappings:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    git:
      mode: full
#logging:
#  level:
#    pers.clare: debug
