spring:
  datasource:
    demo:
      jdbc-url: jdbc:h2:file:./temp/data/h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      driverClassName: org.h2.Driver
      username: sa
      password: 123456
      minimum-idle: 1
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
    slave:
      jdbc-url: jdbc:h2:file:./temp/data/h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      driverClassName: org.h2.Driver
      username: sa
      password: 123456
      minimum-idle: 1
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        web-admin-password: 123456
