spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
    hibernate:
      ddl-auto: create-drop
